#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:t f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:nil title:t toc:nil todo:t |:t
#+TITLE: What is the matrix?
#+DATE: <2019-11-05 Tue>
#+AUTHOR: reconmaster
#+EMAIL: @reconmaster:matrix.org
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.1 (Org mode 9.1.13)
#+LaTeX_HEADER: \usepackage[encapsulated]{CJK}
#+LATEX_HEADER: \usepackage[12pt,letterpaper,top=1in,bottom=1in,left=1in,right=1in]{geometry}
# +LATEX_HEADER: \usepackage{setspace}
# +LATEX_HEADER: \doublespacing

#+begin_export latex
\newcommand{\jntext}[1]{\begin{CJK}{UTF8}{min}#1 \end{CJK}}
#+end_export

\maketitle

Perhaps you have seen the movie /The Matrix/. Neo chooses to take the
red pill and is awakened into a higher-order reality where the world
he lived in was merely a simulation designed to placate the mind while
the body was harnessed as a source of energy.

As you walked out of the theater, perhaps subconsciously rubbing the
back of your neck, you tried to shake a sense of unease. If you were
living in such an artificial world, how would you wake up? If you were
offered a red pill and a blue pill, would you really want to stay in
Wonderland and find out how far the rabbit hole goes?

The matrix is real. If you are truly happy with how the world appears
to work, this is as far as you should go. You can think of me as
Morpheus, and what follows is a schematic for producing a red pill.

You are born into the matrix. At birth, your genetic and pre-natal
environment have already encoded the hardware with which you must
decode the higher-order Reality that exists beyond you. Your senses
provide detectors by which to make observations of the world within
the constraints of what our human biology has evolved to perceive.

What happens after birth, however, is where your senses are
immediately hijacked to imprint the matrix operating system in your
mind. From the first word you learn, the world is broken apart into
the pieces as seen by our ancestors. The programming language of the
matrix is language itself.

Words are powerful. In naming an entity, one simultaneously creates
the potential to manipulate whatever has been named. It was through
words that humans were able to exert their will upon the natural world
and harness the sources of energy that exist therein.

Unfortunately, one of the greatest sources of energy are other human
beings. Slavery and the mechanization of humans allows for tremendous
feats to be accomplished. Slaves built the pyramids in Egypt just as
they build the pyramids in the United States of America.

The amount of power accrued through human bondage is not easily
relinquished. When manacles go out of fashion, how do you continue to
bind the will of another? Words allow you to build worlds into which
people are born where the language they think in traps them in a lower
dimension of the World.

If we do not have a plug in the back of our neck, how do we become
trapped in the matrix? These days, we typically all carry the plug in
our pocket. When we return home in the evenings, we sit to bathe in
more of the soothing light we call media.

The worlds from which this electromagnetic radiation propagates are
artificial. Even that which we think of as news is a manufactured
product that dabbles in fear-based tactics to subvert our evolutionary
wiring and command our attention. This is how the matrix works. To
control people, you simply need to control their minds.

How do you wake up? You must learn to regain control of your thoughts.

Start by carefully tailoring the information streams that enter your
head. Reducing TV and cellphone usage allows you to regain editorial
control of your thoughts and connect with the reality that directly
surrounds you. Learning another language provides you with a new
programming language to manipulate and perceive the world.

If you truly want to disconnect from the matrix of words, /zazen/
(\jntext{座禅}) or sitting meditation is a tool that lets you perceive
the world beyond that which can be described with words. When you
attain /mushin/ (\jntext{無心}) or no mind, you have allowed your
senses to connect directly with the Universe.

Even though I can tell you steps of how to manufacture a red pill, it
is up to you whether or not you want to take it. The world beyond the
constructs of human understanding is a truly beautiful but lonely
place -- words cannot describe it. Not everyone has the discipline or
courage to escape into the Unknown.

The matrix, or society, in its current manifestation is a
self-perpetuating form of modern-day slavery. We are taught to trade
our time as a commodity, a construct of the Industrial Revolution
where people became part of the machine.

We can continue to live in this world where we are symbolically
manipulated as cogs. The status quo is becoming encoded into the
foundation of the new matrix that is now running on artificial
intelligences that are limited by the minds of its architects and the
bias in the data from which it learns.

Or, we can start to wake up so that we can envision a better society
that exists in a reality beyond that which we can currently perceive.

You can take the blue pill and go back to sleep, or you can see where
the red pill takes you and then go help other people wake up.
