#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:t f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:nil title:t toc:nil todo:t |:t
#+TITLE: Что такое матрица?
#+DATE: <2019-11-05 Tue>
#+AUTHOR: reconmaster
#+EMAIL: @reconmaster:matrix.org
#+AUTHOR: tururu
#+EMAIL: @turururu:matrix.org
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.1 (Org mode 9.1.13)
#+LaTeX_HEADER: \usepackage[encapsulated]{CJK}
#+LATEX_HEADER: \usepackage[12pt,letterpaper,top=1in,bottom=1in,left=1in,right=1in]{geometry}
# +LATEX_HEADER: \usepackage{setspace}
# +LATEX_HEADER: \doublespacing

#+begin_export latex
\newcommand{\jntext}[1]{\begin{CJK}{UTF8}{min}#1 \end{CJK}}
#+end_export

\maketitle

Возможно, вы видели фильм "Матрица". По сюжету Нео, главный герой, решает принять красную таблетку, предлложенную Морфеусом, и переносится в новую реальность, этот мир был лишь симуляцией, предназначенной для успокоения разума, а тело использовалось в качестве источника энергии.

Когда вы вышли из театра, возможно, подсознательно потирая затылок, вы пытались избавиться от чувства беспокойства. Если бы вы жили в таком искусственном мире, как бы вы проснулись? Если бы вам предложили красную и синюю таблетки, действительно ли вы захотели бы остаться в Стране Чудес и узнать, как далеко простирается кроличья нора?

Матрица реальна. Если вы действительно довольны тем, как устроен мир, это то, что вам нужно. Вы можете думать обо мне как о Морфеусе. Далее следует схема по изготовлению красной пилюли.

Вы родились в матрице. При рождении ваша генетическая информация уже закодированы в оборудование, с помощь которого вы должны расшифровать реальность более высокого порядка, которая существует вне вас. Детекторы симулируют ваши чувства, ваш мир находится в рамочке.

С того момента, как вы родились, все ваши чувства переносятся в ОС матрицы в вашем разуме. С первого вашего слова, мир, который существовал раньше, разваливается на куски. Язык программирования матрицы - это сам язык.

Слова имеют силу. Именно с помощью слов люди смогли взаимодействовать с миром, преобразовывая внутреннюю энергию.

К сожалению, одним из величайших источников энергии являются люди. Рабство позволяет совершать огромные подвиги. Рабы построили пирамиды в Египте так же, как пирамиды в Соединенных Штатах Америки.

От власти над всем человечеством нелегко отказаться. Когда наручники выходят из моды, как вы продолжаете связывать волю другого? Слова позволяют строить миры, в которых рождаются люди, где язык, на котором они думают, заманивает их в ловушку в более низком измерении.

Если у нас нет вилки на затылке,тогда как же мы попадаем в ловушку матрицы? В наши дни мы носим вилку в кармане. Когда возвращаемся домой вечером, сидим и купаемся в успокаивающем свете, который мы называем медиа.

Миры, из которых распространяется это электромагнитное излучение - искусственны. Даже то, что мы считаем новостями, является промышленным продуктом, который пользуется тактикой, основанной на страхе, чтобы привлечь наше внимание. Так работает матрица. Чтобы управлять людьми, вам просто нужно контролировать их разум.

Как вы просыпаетесь? Вы должны восстановить контроль над собственными мыслями.

Начните с тщательной настройки информационных потоков, поступающих в голову. Сокращение использования телевизора и мобильного телефона позволяет вам восстановить контроль над мыслями и соединиться с реальностью, которая непосредственно вас окружает.

Если вы действительно хотите отключиться от матрицы, дзадзен (медитация, практикуемая в дзен-буддизме) ,или просто медитация, — это лучший выбор который позволит вам воспринимать мир за пределами того, что можно описать словами. Когда вы достигаете мусин ("ум без ума")', вы позволите своим чувствам напрямую соединиться со Вселенной.

Несмотря на то, расскажу ли я вам как изготовить красную таблетку, вам решать, хотите ли вы ее принять. Мир за пределами представлений человеческого понимания — это действительно красивое, но одинокое место, его не описать словами. Не у всех хватит выдержки или мужества, чтобы сбежать в Неизвестное.

Матрица, или общество, в его нынешнем проявлении — это самовоспроизводящаяся форма современного рабства. Нас учат торговать своим временем как товаром, продуктом промышленной революции, когда люди стали частью машины.

Мы можем продолжать жить в этом мире, где нами символически манипулируют как винтиками. Статус quo кодируется в основе новой матрицы, которая теперь работает на искусственном интеллекте, ограниченном разумом его создателей и предвзятостью данных, на которых он учится.

Или мы можем просыпаться, чтобы представить себе лучшее общество, существующее в реальности за пределами той, которую мы можем воспринимать в настоящее время.

Вы можете принять синюю таблетку и снова заснуть, или вы можете увидеть, куда вас приведет красная таблетка, а затем помочь другим людям проснуться.
